class CityList {
  static const List<String> citylist = [
    'Abbottabad',
    'Adilpur',
    'Ahmadpur Sial',
    'Ahmedpur East',
    'Akora',
    'Alik Ghund',
    'Alipur Chatha',
    'Alizai',
    'Aman Garh',
    'Amirabad',
    'Arifwala',
    'Ashanagro Koto',
    'Attock Tehsil',
    'Awaran District',
    'Baddomalhi',
    'Badin',
    'Baffa',
    'Bagarji',
    'Bahawalnagar',
    'Bahawalpur',
    'Bakhri Ahmad Khan',
    'Bandhi',
    'Bannu',
    'Barishal',
    'Barkhan',
    'Barkhan District',
    'Basirpur',
    'Basti Dosa',
    'Bat Khela',
    'Battagram',
    'Battagram District',
    'Begowala',
    'Bela',
    'Berani',
    'Bhag',
    'Bhakkar',
    'Bhalwal',
    'Bhan',
    'Bhawana',
    'Bhera',
    'Bhimbar',
    'Bhiria',
    'Bhit Shah',
    'Bhopalwala',
    'Bozdar Wada',
    'Bulri',
    'Buner District',
    'Burewala',
    'Chagai District',
    'Chak',
    'Chak Azam Saffo',
    'Chak Jhumra',
    'Chak One Hundred Twenty Nine Left',
    'Chak Thirty-one -Eleven Left',
    'Chak Two Hundred Forty-Nine TDA',
    'Chakwal',
    'Chaman',
    'Chamber',
    'Charsadda',
    'Chawinda',
    'Cherat Cantonement',
    'Chhor',
    'Chichawatni',
    'Chiniot',
    'Chishtian',
    'Chitral',
    'Choa Saidanshah',
    'Chowki Jamali',
    'Chuhar Jamali',
    'Chuhar Kana',
    'Chunian',
    'Dadhar',
    'Dadu',
    'Daira Din Panah',
    'Dajal',
    'Dalbandin',
    'Dandot RS',
    'Daromehar',
    'Darya Khan',
    'Darya Khan Marri',
    'Daska',
    'Daud Khel',
    'Daulatpur',
    'Daultala',
    'Daur',
    'Dera Bugti',
    'Dera Bugti District',
    'Dera Ghazi Khan',
    'Dera Ismail Khan',
    'Dera Isma1l Khan District',
    'Dhanot',
    'Dhaunkal',
    'Dhok Awan',
    'Dhoro Naro',
    'Digri',
    'Dijkot',
    'Dinan Bashnoian Wala',
    'Dinga',
    'Dipalpur',
    'Diplo',
    'Doaba',
    'Dokri',
    'Duki',
    'Dullewala',
    'Dunga Bunga',
    'Dunyapur',
    'Eminabad',
    'Faisalabad',
    'Faqirwali',
    'Faruka',
    'Fazilpur',
    'Ferozewala',
    'Fort Abbas',
    'Gadani',
    'Gambat',
    'Garh Maharaja',
    'Garhi Khairo',
    'Garhiyasin',
    'Gharo',
    'Ghauspur',
    'Ghotki',
    'Gilgit',
    'Gojra',
    'Goth Garelo',
    'Goth Phulji',
    'Goth Radhan',
    'Gujar Khan',
    'Gujranwala',
    'Gujranwala Division',
    'Gujrat',
    'Gulishah Kach',
    'Gwadar',
    'Hadali',
    'Hafizabad',
    'Hala',
    'Hangu',
    'Haripur',
    'Harnai',
    'Harnoli',
    'Harunabad',
    'Hasan Abdal',
    'Hasilpur',
    'Haveli Lakha',
    'Havelian',
    'Hazro',
    'Hingorja',
    'Hujra Shah Muqeem',
    'Hyderabad',
    'Islamabad',
    'Islamkot',
    'Jacobabad',
    'Jafarabad District',
    'Jahanian Shah',
    'Jalalpur Jattan',
    'Jalalpur Pirwala',
    'Jam Sahib',
    'Jampur',
    'Jamshoro',
    'Jand',
    'Jandiala Sher Khan',
    'Jaranwala',
    'Jati',
    'Jatoi Shimali',
    'Jauharabad',
    'Jhal Magsi District',
    'Jhang',
    'Jhang Sadar',
    'Jhawarian',
    'Jhelum',
    'Jhol',
    'Jiwani',
    'Johi',
    'Kabirwala',
    'Kadhan',
    'Kahna Nau',
    'Kahuta',
    'Kakad Wari Dir Upper',
    'Kalabagh',
    'Kalaswala',
    'Kalat',
    'Kalat District',
    'Kaleke Mandi',
    'Kallar Kahar',
    'Kalur Kot',
    'Kamalia',
    'Kamar Mushani',
    'Kambar',
    'Kamoke',
    'Kamra',
    'Kandhkot',
    'Kandiari',
    'Kandiaro',
    'Kanganpur',
    'Karachi',
    'Karak',
    'Karaundi',
    'Kario Ghanwar',
    'Karor',
    'Kashmor',
    'Kasur',
    'Keshupur',
    'Keti Bandar',
    'Khadan Khak',
    'Khadro',
    'Khairpur',
    'Khairpur Mir’s',
    'Khairpur Nathan Shah',
    'Khairpur Tamiwali',
    'Khalabat',
    'Khandowa',
    'Khanewal',
    'Khanga Dogran',
    'Khangarh',
    'Khanpur',
    'Khanpur Mahar',
    'Kharan',
    'Kharan District',
    'Kharian',
    'Khewra',
    'Khurrianwala',
    'Khushab',
    'Khuzdar',
    'Khuzdar District',
    'Kohat',
    'Kohlu',
    'Kohror Pakka',
    'Kot Addu Tehsil',
    'Kot Diji',
    'Kot Ghulam Muhammad',
    'Kot Malik Barkhurdar',
    'Kot Mumin',
    'Kot Radha Kishan',
    'Kot Rajkour',
    'Kot Samaba',
    'Kot Sultan',
    'Kotli',
    'Kotli District',
    'Kotli Loharan',
    'Kotri',
    'Kulachi',
    'Kundian',
    'Kunjah',
    'Kunri',
    'Lachi',
    'Ladhewala Waraich',
    'Lahore',
    'Lakhi',
    'Lakki',
    'Lala Musa',
    'Lalian',
    'Landi Kotal',
    'Larkana',
    'Lasbela District',
    'Layyah',
    'Layyah District',
    'Liliani',
    'Lodhran',
    'Loralai',
    'Loralai District',
    'Mach',
    'Madeji',
    'Mailsi',
    'Malakwal',
    'Malakwal City',
    'Malir Cantonment',
    'Mamu Kanjan',
    'Mananwala',
    'Mandi Bahauddin',
    'Mandi Bahauddin District',
    'Mangla',
    'Mankera',
    'Mansehra',
    'Mardan',
    'Mastung',
    'Mastung District',
    'Matiari',
    'Matli',
    'Mehar',
    'Mehmand Chak',
    'Mehrabpur',
    'Mian Channun',
    'Mianke Mor',
    'Mianwali',
    'Minchinabad',
    'Mingora',
    'Miran Shah',
    'Miro Khan',
    'Mirpur Bhtoro',
    'Mirpur District',
    'Mirpur Khas',
    'Mirpur Mathelo',
    'Mirpur Sakro',
    'Mirwah Gorchani',
    'Mitha Tiwana',
    'Mithi',
    'Moro',
    'Moza Shahwala',
    'Multan',
    'Multan District',
    'Muridke',
    'Murree',
    'Musa Khel District',
    'Mustafabad',
    'Muzaffarabad',
    'Muzaffargarh',
    'Nabisar',
    'Nankana Sahib',
    'Narang Mandi',
    'Narowal',
    'Nasirabad',
    'Nas1rabad District',
    'Naudero',
    'Naukot',
    'Naushahra Virkan',
    'Naushahro Firoz',
    'Nawabshah',
    'Nazir Town',
    'New Badah',
    'New Mirpur',
    'Noorabad',
    'North Waz1ristan Agency',
    'Nowshera',
    'Nowshera Cantonment',
    'Nushki',
    'Okara',
    'Ormara',
    'Pabbi',
    'Pad Idan',
    'Paharpur',
    'Pakki Shagwanwali',
    'Pakpattan',
    'Panjgur District',
    'Pano Aqil',
    'Pasni',
    'Pasrur',
    'Pattoki',
    'Peshawar',
    'Phalia',
    'Pind Dadan Khan',
    'Pindi Bhattian',
    'Pindi Gheb',
    'Pir Jo Goth',
    'Pir Mahal',
    'Pishin',
    'Pithoro',
    'Qadirpur Ran',
    'Qila Didar Singh',
    'Qila Saifullah District',
    'Quetta',
    'Quetta District',
    'Rabwah',
    'Rahim Yar Khan',
    'Rahimyar Khan District',
    'Raiwind',
    'Raja Jang',
    'Rajanpur',
    'Rajo Khanani',
    'Ranipur',
    'Rasulnagar',
    'Ratodero',
    'Rawala Kot',
    'Rawalpindi',
    'Rawalpindi District',
    'Renala Khurd',
    'Risalpur Cantonment',
    'Rohri',
    'Rojhan',
    'Rustam',
    'Sadiqabad',
    'Sahiwal',
    'Sakrand',
    'Samaro',
    'Sambrial',
    'Sanghar',
    'Sangla Hill',
    'Sanjwal',
    'Sann',
    'Sarai Alamgir',
    'Sarai Naurang',
    'Sarai Sidhu',
    'Sargodha',
    'Sehwan',
    'Setharja Old',
    'Shabqadar',
    'Shahdad Kot',
    'Shahdadpur',
    'Shahkot Tehsil',
    'Shahpur',
    'Shahpur Chakar',
    'Shahr Sultan',
    'Shakargarh',
    'Sharqpur',
    'Sheikhupura',
    'Shikarpur',
    'Shingli Bala',
    'Shinpokh',
    'Shorkot',
    'Shorkot',
    'Shujaabad',
    'Sialkot',
    'Sibi',
    'Sillanwali',
    'Sinjhoro',
    'S1ta Road',
    'Skardu',
    'Sobhodero',
    'Sodhra',
    'Sohbatpur',
    'South Waz1ristan Agency',
    'Sukheke Mandi',
    'Sukkur',
    'Surab',
    'Surkhpur',
    'Swabi',
    'Talagang',
    'Talamba',
    'Talhar',
    'Tandlianwala',
    'Tando Adam',
    'Tando Allahyar',
    'Tando Bago',
    'Tando Jam',
    'Tando Mitha Khan',
    'Tando Muhammad Khan',
    'Tangi',
    'Tangwani',
    'Tank',
    'Taunsa',
    'Thal',
    'Tharu Shah',
    'Thatta',
    'Thul',
    'Toba Tek Singh',
    'Topi',
    'Turbat',
    'Ubauro',
    'Umarkot',
    'Umerkot',
    'Umerkot District',
    'Upper Dir',
    'Usta Muhammad',
    'Uthal',
    'Utmanzai',
    'Vihari',
    'Wah',
    'Wana',
    'Warah',
    'Warburton',
    'Wazirabad',
    'West Punjab',
    'Yazman',
    'Zafarwal',
    'Zahir Pir',
    'Zaida',
    'Zhob',
    'Zhob District',
    'Ziarat',
    'Ziarat District',
  ];
}
